import type { Procedure } from '@/types'

// Dental procedures library
export const DENTAL_PROCEDURES: Procedure[] = [
  {
    id: 'dental-implant',
    industry: 'dental',
    category: 'implants',
    name: 'Dental Implant',
    description: 'A titanium post surgically placed into the jawbone to replace a missing tooth root.',
    duration_min: 60,
    plain_english: 'We replace your missing tooth with a permanent artificial root made of titanium, then attach a crown that looks and feels like a real tooth.',
    steps: [
      'Consultation & 3D X-ray imaging',
      'Titanium post placed into jawbone',
      '3–6 month healing (osseointegration)',
      'Abutment attachment',
      'Custom crown placed',
    ],
    benefits: [
      'Looks and functions like a natural tooth',
      'Prevents bone loss in jaw',
      'Lasts 20+ years with proper care',
      'No impact on neighboring teeth',
    ],
    aftercare: [
      'Soft foods for 1 week post-surgery',
      'No smoking — slows healing significantly',
      'Rinse with warm saltwater 3x daily',
      'Avoid strenuous activity for 48 hours',
    ],
    faq: [
      { q: 'Does it hurt?', a: 'The procedure is done under local anesthesia. Most patients report less discomfort than a tooth extraction.' },
      { q: 'How long does it last?', a: 'Dental implants are designed to last a lifetime with proper care and regular dental visits.' },
      { q: 'Am I a candidate?', a: 'Most adults with good general health qualify. We check bone density and gum health during your consultation.' },
      { q: 'Does insurance cover it?', a: 'Many plans now cover a portion of implant costs. We will verify your benefits before treatment.' },
    ],
    image_query: 'dental implant procedure diagram',
    consent_required: true,
    tags: ['surgical', 'restorative', 'permanent'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'teeth-whitening',
    industry: 'dental',
    category: 'cosmetic',
    name: 'Professional Teeth Whitening',
    description: 'In-office bleaching treatment that removes deep stains and lightens teeth by up to 8 shades.',
    duration_min: 90,
    plain_english: 'We apply a professional-grade whitening gel to your teeth and use a special light to activate it — getting you a dramatically whiter smile in a single visit.',
    steps: [
      'Shade assessment and photography',
      'Gum protection applied',
      'Whitening gel applied to teeth',
      'LED light activation (3 × 15-min cycles)',
      'Final shade comparison',
    ],
    benefits: [
      'Up to 8 shades whiter in one visit',
      'Safe, professionally supervised',
      'Results last 1–3 years',
      'Immediate, visible results',
    ],
    aftercare: [
      'Avoid coffee, tea, red wine for 48 hours',
      'No smoking for 48 hours',
      'Use sensitivity toothpaste if needed',
      'Touch-up trays provided for home use',
    ],
    faq: [
      { q: 'Will my teeth be sensitive?', a: 'Some temporary sensitivity is normal and resolves within 24–48 hours.' },
      { q: 'How white will my teeth get?', a: 'Results vary by natural tooth color, but most patients see 4–8 shades improvement.' },
      { q: 'How long do results last?', a: 'With good oral hygiene and periodic touch-ups, results last 1–3 years.' },
    ],
    image_query: 'teeth whitening before after smile',
    consent_required: false,
    tags: ['cosmetic', 'same-day', 'non-surgical'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'invisalign',
    industry: 'dental',
    category: 'orthodontics',
    name: 'Invisalign Clear Aligners',
    description: 'Custom-made clear plastic aligners that gradually straighten teeth without metal braces.',
    duration_min: 45,
    plain_english: 'Instead of metal braces, we use a series of clear, removable trays that gradually shift your teeth into perfect alignment — most people won\'t even know you\'re wearing them.',
    steps: [
      'Digital 3D scan of your teeth',
      'Custom treatment plan + simulation',
      'First set of aligners fitted',
      'New tray set every 1–2 weeks',
      'Regular check-ins every 6–8 weeks',
      'Retainer for long-term results',
    ],
    benefits: [
      'Nearly invisible — no metal braces',
      'Removable for eating and cleaning',
      'Typically faster than traditional braces',
      'No food restrictions',
    ],
    aftercare: [
      'Wear aligners 20–22 hours per day',
      'Remove only to eat, drink (except water), and clean',
      'Clean aligners with clear soap — not toothpaste',
      'Wear retainer after treatment completes',
    ],
    faq: [
      { q: 'How long does treatment take?', a: 'Most cases complete in 6–18 months depending on complexity.' },
      { q: 'Can I eat normally?', a: 'Yes — remove your aligners before eating anything, then brush before putting them back.' },
      { q: 'Are they really invisible?', a: 'They are very difficult to notice in normal conversation. Most adults prefer them for this reason.' },
    ],
    image_query: 'Invisalign clear aligners smile transformation',
    consent_required: true,
    tags: ['orthodontics', 'cosmetic', 'removable'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'porcelain-veneers',
    industry: 'dental',
    category: 'cosmetic',
    name: 'Porcelain Veneers',
    description: 'Ultra-thin custom porcelain shells bonded to the front of teeth to improve shape, color, and size.',
    duration_min: 120,
    plain_english: 'Think of veneers like a custom cover for the front of your teeth — we bond ultra-thin porcelain shells that completely transform your smile\'s appearance in just two visits.',
    steps: [
      'Smile design consultation',
      'Small amount of enamel removed (0.5mm)',
      'Impressions taken for lab fabrication',
      'Temporary veneers placed',
      'Custom veneers bonded permanently',
    ],
    benefits: [
      'Dramatic smile transformation',
      'Fixes chips, stains, gaps, and shape',
      'Natural-looking porcelain',
      'Stain-resistant surface',
      'Lasts 10–15 years',
    ],
    aftercare: [
      'Avoid biting hard objects (ice, pens, nails)',
      'Use non-abrasive toothpaste',
      'Wear night guard if you grind',
      'Regular cleaning visits every 6 months',
    ],
    faq: [
      { q: 'Is it permanent?', a: 'Veneers require removing a small amount of enamel, making them a permanent commitment.' },
      { q: 'How many teeth need veneers?', a: 'Most smile makeovers involve 6–10 veneers to create a balanced, natural look.' },
      { q: 'Do they look natural?', a: 'Modern porcelain veneers are virtually indistinguishable from natural teeth.' },
    ],
    image_query: 'porcelain veneers smile makeover before after',
    consent_required: true,
    tags: ['cosmetic', 'permanent', 'smile-makeover'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'root-canal',
    industry: 'dental',
    category: 'restorative',
    name: 'Root Canal Treatment',
    description: 'Removes infected pulp from inside a tooth to save it from extraction.',
    duration_min: 90,
    plain_english: 'A root canal removes the infected nerve tissue inside your tooth that\'s causing pain — we clean, seal, and cap the tooth so you keep it for life instead of losing it.',
    steps: [
      'X-ray to assess infection extent',
      'Local anesthesia applied',
      'Pulp chamber opened',
      'Infected tissue removed and canals cleaned',
      'Canals sealed with biocompatible material',
      'Crown placed to protect the tooth',
    ],
    benefits: [
      'Saves your natural tooth',
      'Eliminates infection and pain',
      'Prevents spread to neighboring teeth',
      'Restored tooth functions normally',
    ],
    aftercare: [
      'Take prescribed antibiotics if given',
      'Avoid chewing on treated side until crown placed',
      'OTC pain relievers for 24–48 hours if needed',
      'Return for crown placement as scheduled',
    ],
    faq: [
      { q: 'Does a root canal hurt?', a: 'With modern anesthesia, a root canal is no more uncomfortable than getting a filling.' },
      { q: 'Why not just extract the tooth?', a: 'Keeping your natural tooth is always the best option — it maintains bite alignment and prevents bone loss.' },
      { q: 'How long does it take?', a: 'Most root canals are completed in 1–2 appointments of 60–90 minutes each.' },
    ],
    image_query: 'root canal treatment tooth anatomy diagram',
    consent_required: true,
    tags: ['restorative', 'endodontic', 'pain-relief'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'dental-crown',
    industry: 'dental',
    category: 'restorative',
    name: 'Dental Crown',
    description: 'A custom cap placed over a damaged tooth to restore its shape, strength, and appearance.',
    duration_min: 60,
    plain_english: 'A crown is like a protective cap that fits over a damaged or weakened tooth — it restores its full function and appearance so it looks and works like new.',
    steps: [
      'Tooth prepared (reshaped to fit crown)',
      'Digital or physical impression taken',
      'Temporary crown placed',
      'Custom crown fabricated in lab (1–2 weeks)',
      'Permanent crown cemented in place',
    ],
    benefits: [
      'Protects cracked or weakened teeth',
      'Restores full chewing ability',
      'Covers discolored or misshapen teeth',
      'Lasts 10–15 years',
    ],
    aftercare: [
      'Avoid sticky or hard foods for 24 hours after cementation',
      'Floss carefully around the crown',
      'Same-day sensitivity is normal and resolves quickly',
    ],
    faq: [
      { q: 'How long will my crown last?', a: 'With proper care, dental crowns last 10–15 years or longer.' },
      { q: 'Is it covered by insurance?', a: 'Crowns for restorative purposes (decay, fracture) are typically covered 50–80% by insurance.' },
    ],
    image_query: 'dental crown procedure before after',
    consent_required: false,
    tags: ['restorative', 'protective', 'cosmetic'],
    created_at: new Date().toISOString(),
  },
]

// Salon procedures library
export const SALON_PROCEDURES: Procedure[] = [
  {
    id: 'balayage',
    industry: 'salon',
    category: 'color',
    name: 'Balayage Color',
    description: 'Hand-painted highlighting technique that creates a natural, sun-kissed gradient effect.',
    duration_min: 150,
    plain_english: 'We hand-paint color onto your hair to create natural-looking, low-maintenance highlights that grow out beautifully — no harsh lines at the roots.',
    steps: [
      'Consultation and color selection',
      'Hair sectioned',
      'Color hand-painted onto sections',
      'Processing time (30–45 min)',
      'Toner applied for tone refinement',
      'Blow-dry and style',
    ],
    benefits: [
      'Natural, sun-kissed look',
      'Low-maintenance — grows out gracefully',
      'Fully customizable to your skin tone',
      'No harsh root lines',
    ],
    aftercare: [
      'Use color-safe, sulfate-free shampoo',
      'Deep condition weekly',
      'Avoid washing for 48 hours after service',
      'Touch-ups every 3–4 months',
    ],
    faq: [
      { q: 'How is balayage different from highlights?', a: 'Balayage is hand-painted for a softer, more natural look. Traditional highlights use foils for more uniform lift.' },
      { q: 'How often do I need to come back?', a: 'Every 3–4 months, compared to 6–8 weeks for traditional highlights.' },
    ],
    image_query: 'balayage hair color transformation',
    consent_required: false,
    tags: ['color', 'highlights', 'low-maintenance'],
    created_at: new Date().toISOString(),
  },
]

// Cosmetic procedures library
export const COSMETIC_PROCEDURES: Procedure[] = [
  {
    id: 'rhinoplasty',
    industry: 'cosmetic',
    category: 'facial',
    name: 'Rhinoplasty (Nose Reshaping)',
    description: 'Surgical procedure to reshape the nose for aesthetic or functional improvement.',
    duration_min: 180,
    plain_english: 'Rhinoplasty reshapes your nose to better match your facial features — whether that\'s reducing the size, refining the tip, or correcting a deviated septum that affects breathing.',
    steps: [
      'Consultation and 3D imaging simulation',
      'Medical clearance',
      'General or local anesthesia with sedation',
      'Incisions made inside nostrils (closed) or across the base (open)',
      'Bone and cartilage reshaped',
      'Incisions closed, splint applied',
      '1–2 week recovery with splint',
    ],
    benefits: [
      'Permanent results',
      'Improves facial harmony and proportion',
      'Can correct breathing issues simultaneously',
      'High patient satisfaction rate',
    ],
    aftercare: [
      'Splint worn for 1–2 weeks',
      'No strenuous activity for 3–4 weeks',
      'Sleep with head elevated for 2 weeks',
      'Avoid sun exposure on nose for 6 months',
      'Final results visible at 12 months',
    ],
    faq: [
      { q: 'How long until I see final results?', a: 'Swelling resolves over 12 months — most patients see ~80% of results at 3 months.' },
      { q: 'Is it painful?', a: 'Discomfort is well-managed with prescribed medication. Most patients describe it as pressure, not pain.' },
      { q: 'How old do I need to be?', a: 'We recommend waiting until facial growth is complete — typically 16–18 for females, 17–19 for males.' },
    ],
    image_query: 'rhinoplasty nose reshaping before after profile',
    consent_required: true,
    tags: ['surgical', 'facial', 'permanent'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'hair-transplant',
    industry: 'cosmetic',
    category: 'hair',
    name: 'FUE Hair Transplant',
    description: 'Follicular Unit Extraction — individual hair follicles transplanted to restore natural hairline.',
    duration_min: 480,
    plain_english: 'We individually extract healthy hair follicles from the back of your head — where hair is permanent — and precisely implant them in thinning or bald areas to restore a natural-looking hairline.',
    steps: [
      'Hairline design consultation',
      'Donor area shaved and numbed',
      'Follicles individually extracted with micro-punch',
      'Recipient sites created at correct angle and density',
      'Follicles implanted one by one',
      'Healing begins immediately',
    ],
    benefits: [
      'Permanent, natural-looking results',
      'Uses your own hair — no rejection',
      'No linear scar',
      'Can style and cut normally after healing',
    ],
    aftercare: [
      'Sleep upright for 3–5 days',
      'No touching the grafts for 2 weeks',
      'Shedding at 2–4 weeks is normal (shock loss)',
      'New growth visible at 4–6 months',
      'Full results at 12–18 months',
    ],
    faq: [
      { q: 'When will I see results?', a: 'Hair begins growing at 4–6 months. Full, final results are visible at 12–18 months.' },
      { q: 'Is the transplanted hair permanent?', a: 'Yes — follicles from the donor zone are genetically resistant to hair loss.' },
      { q: 'How many grafts do I need?', a: 'Varies by area — typically 1,500–3,500 grafts for hairline restoration. We assess during consultation.' },
    ],
    image_query: 'hair transplant FUE before after hairline',
    consent_required: true,
    tags: ['surgical', 'hair', 'permanent'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'breast-augmentation',
    industry: 'cosmetic',
    category: 'breast',
    name: 'Breast Augmentation',
    description: 'Surgical placement of implants to enhance breast size, shape, and symmetry.',
    duration_min: 120,
    plain_english: 'We use implants or fat transfer to enhance your breast size and shape — creating natural-feeling results tailored to your body type and goals.',
    steps: [
      'Consultation — size, shape, and implant type selection',
      '3D imaging simulation',
      'Medical clearance and pre-op labs',
      'General anesthesia administered',
      'Incision made (typically in crease)',
      'Implant placed and positioned',
      'Incisions closed, surgical bra fitted',
    ],
    benefits: [
      'Significant, customizable enhancement',
      'Improves symmetry',
      'Natural look and feel with modern implants',
      'High patient satisfaction',
    ],
    aftercare: [
      'Wear surgical bra 24/7 for 4–6 weeks',
      'No lifting over 10 lbs for 4 weeks',
      'No strenuous activity for 6 weeks',
      'Sleep on back for 6 weeks',
      'Scar maturation takes 12–18 months',
    ],
    faq: [
      { q: 'How long do implants last?', a: 'Modern implants are designed to last 10–20 years. Replacement is not automatically required but may be desired.' },
      { q: 'Saline vs. silicone?', a: 'Silicone implants feel more natural and are the most popular choice. We discuss both options in your consultation.' },
      { q: 'Will I lose nipple sensation?', a: 'Temporary changes in sensation are possible. Most patients return to normal feeling within 3–6 months.' },
    ],
    image_query: 'breast augmentation before after natural results',
    consent_required: true,
    tags: ['surgical', 'breast', 'enhancement'],
    created_at: new Date().toISOString(),
  },
]

export const ALL_PROCEDURES: Procedure[] = [
  ...DENTAL_PROCEDURES,
  ...SALON_PROCEDURES,
  ...COSMETIC_PROCEDURES,
]

export function getProceduresByIndustry(industry: string): Procedure[] {
  return ALL_PROCEDURES.filter((p) => p.industry === industry)
}

export function getProcedureById(id: string): Procedure | undefined {
  return ALL_PROCEDURES.find((p) => p.id === id)
}

export function getProceduresByCategory(industry: string, category: string): Procedure[] {
  return ALL_PROCEDURES.filter((p) => p.industry === industry && p.category === category)
}
