import type { Procedure } from '@/types'

// ─────────────────────────────────────────────
// DENTAL — 14 procedures
// ─────────────────────────────────────────────
export const DENTAL_PROCEDURES: Procedure[] = [
  {
    id: 'dental-implant',
    industry: 'dental',
    category: 'implants',
    name: 'Dental Implant',
    description: 'A titanium post surgically placed into the jawbone to replace a missing tooth root.',
    duration_min: 60,
    plain_english: 'We replace your missing tooth with a permanent artificial root made of titanium, then attach a crown that looks and feels like a real tooth.',
    steps: [
      'Consultation & 3D X-ray imaging',
      'Titanium post placed into jawbone',
      '3–6 month healing (osseointegration)',
      'Abutment attachment',
      'Custom crown placed',
    ],
    benefits: [
      'Looks and functions like a natural tooth',
      'Prevents bone loss in jaw',
      'Lasts 20+ years with proper care',
      'No impact on neighboring teeth',
    ],
    aftercare: [
      'Soft foods for 1 week post-surgery',
      'No smoking — slows healing significantly',
      'Rinse with warm saltwater 3x daily',
      'Avoid strenuous activity for 48 hours',
    ],
    faq: [
      { q: 'Does it hurt?', a: 'The procedure is done under local anesthesia. Most patients report less discomfort than a tooth extraction.' },
      { q: 'How long does it last?', a: 'Dental implants are designed to last a lifetime with proper care and regular dental visits.' },
      { q: 'Am I a candidate?', a: 'Most adults with good general health qualify. We check bone density and gum health during your consultation.' },
      { q: 'Does insurance cover it?', a: 'Many plans now cover a portion of implant costs. We will verify your benefits before treatment.' },
    ],
    image_query: 'dental implant procedure diagram',
    consent_required: true,
    tags: ['surgical', 'restorative', 'permanent'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'implant-supported-bridge',
    industry: 'dental',
    category: 'implants',
    name: 'Implant-Supported Bridge',
    description: 'Two implants anchor a bridge to replace multiple consecutive missing teeth without affecting adjacent healthy teeth.',
    duration_min: 90,
    plain_english: 'Instead of a traditional bridge that clips onto healthy teeth, we anchor the bridge to implants — your healthy neighboring teeth stay untouched and you get a permanent, stable replacement.',
    steps: [
      'Full mouth X-ray and CT scan',
      'Two implant posts placed in jawbone',
      '3–6 months healing',
      'Custom bridge fabricated',
      'Bridge secured onto implant abutments',
    ],
    benefits: [
      'Replaces multiple teeth with just two implants',
      'Neighboring teeth are not shaved down',
      'Fixed — does not come out like dentures',
      'Natural chewing strength restored',
    ],
    aftercare: [
      'Use floss threaders or water flosser under bridge',
      'Avoid hard or crunchy foods for first 2 weeks',
      'Regular hygienist visits every 3–4 months',
    ],
    faq: [
      { q: 'How many missing teeth can this replace?', a: 'Typically 2–4 consecutive teeth with two implants as anchors.' },
      { q: 'Is it removable?', a: 'No — it is fixed permanently like natural teeth.' },
    ],
    image_query: 'implant supported bridge diagram',
    consent_required: true,
    tags: ['surgical', 'implants', 'bridge', 'restorative'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'all-on-4',
    industry: 'dental',
    category: 'implants',
    name: 'All-on-4 Full Arch Restoration',
    description: 'Four implants support a full fixed arch of teeth — a complete smile replacement in a single procedure.',
    duration_min: 240,
    plain_english: 'All-on-4 replaces an entire arch of missing or failing teeth with just four implants. You leave the same day with a fixed, functional smile — no dentures, no waiting months.',
    steps: [
      '3D CT scan and full digital planning',
      'Any remaining teeth removed if needed',
      'Four implants precisely placed in jaw',
      'Temporary full arch attached same day',
      '3–6 months healing',
      'Final permanent arch fitted',
    ],
    benefits: [
      'Full arch of teeth in one day',
      'Fixed — never comes out',
      'Only four implants needed (cost-effective)',
      'Bone grafting often not required',
      'Immediate function — eat same day',
    ],
    aftercare: [
      'Soft diet for 3 months during healing',
      'Water flosser essential for hygiene',
      'No smoking throughout healing',
      'Annual implant check-ups',
    ],
    faq: [
      { q: 'Can I eat the same day?', a: 'Yes — soft foods immediately. Regular foods after the permanent arch is placed.' },
      { q: 'How is this different from dentures?', a: 'All-on-4 is permanently fixed to your jaw — no adhesives, no slipping, no removing at night.' },
      { q: 'What if I do not have enough bone?', a: 'All-on-4 is specifically designed to work with reduced bone — tilted implants maximize contact without grafting in most cases.' },
    ],
    image_query: 'all on 4 dental implants full arch before after',
    consent_required: true,
    tags: ['surgical', 'implants', 'full-arch', 'same-day'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'teeth-whitening',
    industry: 'dental',
    category: 'cosmetic',
    name: 'Professional Teeth Whitening',
    description: 'In-office bleaching treatment that removes deep stains and lightens teeth by up to 8 shades.',
    duration_min: 90,
    plain_english: 'We apply a professional-grade whitening gel to your teeth and use a special light to activate it — getting you a dramatically whiter smile in a single visit.',
    steps: [
      'Shade assessment and photography',
      'Gum protection applied',
      'Whitening gel applied to teeth',
      'LED light activation (3 × 15-min cycles)',
      'Final shade comparison',
    ],
    benefits: [
      'Up to 8 shades whiter in one visit',
      'Safe, professionally supervised',
      'Results last 1–3 years',
      'Immediate, visible results',
    ],
    aftercare: [
      'Avoid coffee, tea, red wine for 48 hours',
      'No smoking for 48 hours',
      'Use sensitivity toothpaste if needed',
      'Touch-up trays provided for home use',
    ],
    faq: [
      { q: 'Will my teeth be sensitive?', a: 'Some temporary sensitivity is normal and resolves within 24–48 hours.' },
      { q: 'How white will my teeth get?', a: 'Results vary by natural tooth color, but most patients see 4–8 shades improvement.' },
      { q: 'How long do results last?', a: 'With good oral hygiene and periodic touch-ups, results last 1–3 years.' },
    ],
    image_query: 'teeth whitening before after smile',
    consent_required: false,
    tags: ['cosmetic', 'same-day', 'non-surgical'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'invisalign',
    industry: 'dental',
    category: 'orthodontics',
    name: 'Invisalign Clear Aligners',
    description: 'Custom-made clear plastic aligners that gradually straighten teeth without metal braces.',
    duration_min: 45,
    plain_english: 'Instead of metal braces, we use a series of clear, removable trays that gradually shift your teeth into perfect alignment — most people won\'t even know you\'re wearing them.',
    steps: [
      'Digital 3D scan of your teeth',
      'Custom treatment plan + simulation',
      'First set of aligners fitted',
      'New tray set every 1–2 weeks',
      'Regular check-ins every 6–8 weeks',
      'Retainer for long-term results',
    ],
    benefits: [
      'Nearly invisible — no metal braces',
      'Removable for eating and cleaning',
      'Typically faster than traditional braces',
      'No food restrictions',
    ],
    aftercare: [
      'Wear aligners 20–22 hours per day',
      'Remove only to eat, drink (except water), and clean',
      'Clean aligners with clear soap — not toothpaste',
      'Wear retainer after treatment completes',
    ],
    faq: [
      { q: 'How long does treatment take?', a: 'Most cases complete in 6–18 months depending on complexity.' },
      { q: 'Can I eat normally?', a: 'Yes — remove your aligners before eating anything, then brush before putting them back.' },
      { q: 'Are they really invisible?', a: 'They are very difficult to notice in normal conversation. Most adults prefer them for this reason.' },
    ],
    image_query: 'Invisalign clear aligners smile transformation',
    consent_required: true,
    tags: ['orthodontics', 'cosmetic', 'removable'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'porcelain-veneers',
    industry: 'dental',
    category: 'cosmetic',
    name: 'Porcelain Veneers',
    description: 'Ultra-thin custom porcelain shells bonded to the front of teeth to improve shape, color, and size.',
    duration_min: 120,
    plain_english: 'Think of veneers like a custom cover for the front of your teeth — we bond ultra-thin porcelain shells that completely transform your smile\'s appearance in just two visits.',
    steps: [
      'Smile design consultation',
      'Small amount of enamel removed (0.5mm)',
      'Impressions taken for lab fabrication',
      'Temporary veneers placed',
      'Custom veneers bonded permanently',
    ],
    benefits: [
      'Dramatic smile transformation',
      'Fixes chips, stains, gaps, and shape',
      'Natural-looking porcelain',
      'Stain-resistant surface',
      'Lasts 10–15 years',
    ],
    aftercare: [
      'Avoid biting hard objects (ice, pens, nails)',
      'Use non-abrasive toothpaste',
      'Wear night guard if you grind',
      'Regular cleaning visits every 6 months',
    ],
    faq: [
      { q: 'Is it permanent?', a: 'Veneers require removing a small amount of enamel, making them a permanent commitment.' },
      { q: 'How many teeth need veneers?', a: 'Most smile makeovers involve 6–10 veneers to create a balanced, natural look.' },
      { q: 'Do they look natural?', a: 'Modern porcelain veneers are virtually indistinguishable from natural teeth.' },
    ],
    image_query: 'porcelain veneers smile makeover before after',
    consent_required: true,
    tags: ['cosmetic', 'permanent', 'smile-makeover'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'composite-bonding',
    industry: 'dental',
    category: 'cosmetic',
    name: 'Composite Bonding',
    description: 'Tooth-colored resin applied and sculpted directly onto teeth to repair chips, gaps, and discoloration.',
    duration_min: 60,
    plain_english: 'We apply a tooth-colored putty directly to your tooth, shape it to perfection, and harden it with a special light — fixing chips, gaps, or staining in a single appointment with no drilling.',
    steps: [
      'Shade matching to your natural teeth',
      'Tooth surface lightly roughened',
      'Bonding resin applied in layers',
      'Sculpted to desired shape',
      'Hardened with UV light',
      'Polished for a natural finish',
    ],
    benefits: [
      'Same-day results — no lab wait',
      'No drilling or anesthesia in most cases',
      'Reversible — enamel stays intact',
      'Cost-effective alternative to veneers',
    ],
    aftercare: [
      'Avoid staining foods/drinks for 48 hours',
      'Do not bite nails or chew ice',
      'Polish may need refreshing every 3–5 years',
    ],
    faq: [
      { q: 'How is bonding different from veneers?', a: 'Bonding is applied directly and is reversible. Veneers are lab-made and require enamel removal — but last longer.' },
      { q: 'Does it stain?', a: 'Composite resin can stain over time, especially with coffee and red wine. Polishing restores the brightness.' },
    ],
    image_query: 'composite bonding teeth before after smile',
    consent_required: false,
    tags: ['cosmetic', 'same-day', 'reversible', 'no-drilling'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'root-canal',
    industry: 'dental',
    category: 'restorative',
    name: 'Root Canal Treatment',
    description: 'Removes infected pulp from inside a tooth to save it from extraction.',
    duration_min: 90,
    plain_english: 'A root canal removes the infected nerve tissue inside your tooth that\'s causing pain — we clean, seal, and cap the tooth so you keep it for life instead of losing it.',
    steps: [
      'X-ray to assess infection extent',
      'Local anesthesia applied',
      'Pulp chamber opened',
      'Infected tissue removed and canals cleaned',
      'Canals sealed with biocompatible material',
      'Crown placed to protect the tooth',
    ],
    benefits: [
      'Saves your natural tooth',
      'Eliminates infection and pain',
      'Prevents spread to neighboring teeth',
      'Restored tooth functions normally',
    ],
    aftercare: [
      'Take prescribed antibiotics if given',
      'Avoid chewing on treated side until crown placed',
      'OTC pain relievers for 24–48 hours if needed',
      'Return for crown placement as scheduled',
    ],
    faq: [
      { q: 'Does a root canal hurt?', a: 'With modern anesthesia, a root canal is no more uncomfortable than getting a filling.' },
      { q: 'Why not just extract the tooth?', a: 'Keeping your natural tooth is always the best option — it maintains bite alignment and prevents bone loss.' },
      { q: 'How long does it take?', a: 'Most root canals are completed in 1–2 appointments of 60–90 minutes each.' },
    ],
    image_query: 'root canal treatment tooth anatomy diagram',
    consent_required: true,
    tags: ['restorative', 'endodontic', 'pain-relief'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'dental-crown',
    industry: 'dental',
    category: 'restorative',
    name: 'Dental Crown',
    description: 'A custom cap placed over a damaged tooth to restore its shape, strength, and appearance.',
    duration_min: 60,
    plain_english: 'A crown is like a protective cap that fits over a damaged or weakened tooth — it restores its full function and appearance so it looks and works like new.',
    steps: [
      'Tooth prepared (reshaped to fit crown)',
      'Digital or physical impression taken',
      'Temporary crown placed',
      'Custom crown fabricated in lab (1–2 weeks)',
      'Permanent crown cemented in place',
    ],
    benefits: [
      'Protects cracked or weakened teeth',
      'Restores full chewing ability',
      'Covers discolored or misshapen teeth',
      'Lasts 10–15 years',
    ],
    aftercare: [
      'Avoid sticky or hard foods for 24 hours after cementation',
      'Floss carefully around the crown',
      'Same-day sensitivity is normal and resolves quickly',
    ],
    faq: [
      { q: 'How long will my crown last?', a: 'With proper care, dental crowns last 10–15 years or longer.' },
      { q: 'Is it covered by insurance?', a: 'Crowns for restorative purposes (decay, fracture) are typically covered 50–80% by insurance.' },
    ],
    image_query: 'dental crown procedure before after',
    consent_required: false,
    tags: ['restorative', 'protective', 'cosmetic'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'tooth-extraction',
    industry: 'dental',
    category: 'oral-surgery',
    name: 'Tooth Extraction',
    description: 'Removal of a tooth that cannot be saved due to damage, decay, or overcrowding.',
    duration_min: 45,
    plain_english: 'Sometimes the best option is to remove a tooth that is too damaged to save — we make the process quick and comfortable, and can discuss replacement options like implants right away.',
    steps: [
      'X-ray to assess root shape and position',
      'Local anesthesia applied',
      'Tooth loosened with dental elevator',
      'Tooth removed with forceps',
      'Gauze placed to control bleeding',
      'Aftercare instructions provided',
    ],
    benefits: [
      'Eliminates pain from severely damaged tooth',
      'Prevents infection from spreading',
      'Creates space for orthodontic treatment if needed',
      'Quick procedure with fast recovery',
    ],
    aftercare: [
      'Bite on gauze for 30–45 minutes',
      'No smoking or straws for 72 hours (dry socket risk)',
      'Soft foods for 3–5 days',
      'Avoid the area when brushing for 24 hours',
      'Apply ice pack to cheek for first 24 hours',
    ],
    faq: [
      { q: 'Is it painful?', a: 'You will feel pressure but not pain. We ensure you are fully numb before starting.' },
      { q: 'What about replacing the tooth?', a: 'We recommend discussing implant options at the same appointment to preserve the bone space.' },
      { q: 'What is dry socket?', a: 'A rare complication where the blood clot dislodges — we discuss prevention and are here if it occurs.' },
    ],
    image_query: 'tooth extraction dental procedure',
    consent_required: true,
    tags: ['oral-surgery', 'extraction', 'restorative'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'wisdom-teeth',
    industry: 'dental',
    category: 'oral-surgery',
    name: 'Wisdom Tooth Removal',
    description: 'Surgical removal of third molars that are impacted, infected, or causing crowding.',
    duration_min: 60,
    plain_english: 'Wisdom teeth are the last four molars to come in — and most people don\'t have room for them. We remove them before they cause pain, infection, or push your other teeth out of alignment.',
    steps: [
      'Panoramic X-ray to see all four wisdom teeth',
      'Local anesthesia (sedation available)',
      'Incision made if tooth is impacted',
      'Tooth sectioned and removed in pieces if needed',
      'Site cleaned and sutured',
      'Recovery instructions provided',
    ],
    benefits: [
      'Prevents future pain and infections',
      'Protects alignment of existing teeth',
      'Eliminates recurring jaw pain or swelling',
      'One-time procedure — they will not grow back',
    ],
    aftercare: [
      'Rest for 24–48 hours',
      'Ice pack to cheek for first day',
      'Soft foods (soup, yogurt, smoothies) for 5 days',
      'No straws or smoking — dry socket risk',
      'Rinse gently with saltwater from day 2',
      'Return for suture removal at 1 week if needed',
    ],
    faq: [
      { q: 'Do I need all four removed at once?', a: 'We usually recommend removing all at once for one recovery period, but we can split it if you prefer.' },
      { q: 'Can I be sedated?', a: 'Yes — we offer nitrous oxide, oral sedation, and IV sedation options. We recommend discussing this at your consultation.' },
      { q: 'How long is recovery?', a: 'Most patients feel normal within 3–5 days. Full healing takes 2–4 weeks.' },
    ],
    image_query: 'wisdom tooth removal impacted X-ray',
    consent_required: true,
    tags: ['oral-surgery', 'wisdom-teeth', 'extraction'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'gum-disease-treatment',
    industry: 'dental',
    category: 'preventive',
    name: 'Deep Cleaning (Scaling & Root Planing)',
    description: 'Non-surgical treatment for gum disease — removes tartar and bacteria from below the gumline.',
    duration_min: 90,
    plain_english: 'When gum disease goes below the gumline, a regular cleaning can\'t reach it. We do a deep cleaning that removes the hardened plaque and bacteria causing your gums to recede — stopping the disease before it damages your bone.',
    steps: [
      'Full-mouth X-rays and gum pocket measurements',
      'Local anesthetic applied',
      'Tartar removed from below the gumline (scaling)',
      'Root surfaces smoothed (planing) to discourage bacteria',
      'Antibacterial rinse applied',
      'Follow-up appointment scheduled in 4–6 weeks',
    ],
    benefits: [
      'Halts gum disease progression',
      'Reduces gum pocket depths',
      'Prevents tooth and bone loss',
      'Improves breath caused by bacterial infection',
    ],
    aftercare: [
      'Gums may be sore for 2–3 days — ibuprofen helps',
      'Use a soft-bristled toothbrush',
      'Rinse with warm saltwater twice daily',
      'Avoid hard or crunchy foods for 48 hours',
      'Maintain 3-month hygiene appointments going forward',
    ],
    faq: [
      { q: 'Is this the same as a regular cleaning?', a: 'No — a regular cleaning only cleans above the gumline. Scaling and root planing goes below, where gum disease lives.' },
      { q: 'Will my gums grow back?', a: 'Gums that have receded cannot regrow, but treatment stops further recession and allows the tissue to reattach.' },
      { q: 'Do I need surgery after this?', a: 'For most patients, deep cleaning controls gum disease without surgery. We reassess at your follow-up appointment.' },
    ],
    image_query: 'periodontal deep cleaning gum disease treatment',
    consent_required: false,
    tags: ['preventive', 'gum-disease', 'periodontal'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'dental-bridge',
    industry: 'dental',
    category: 'restorative',
    name: 'Traditional Dental Bridge',
    description: 'A fixed prosthetic that uses adjacent teeth as anchors to bridge the gap from a missing tooth.',
    duration_min: 60,
    plain_english: 'A bridge is like a false tooth held in place by crowns on the teeth on either side of the gap — it fills the space, restores your bite, and looks completely natural.',
    steps: [
      'Neighboring teeth prepared (reshaped) for crowns',
      'Impressions taken',
      'Temporary bridge placed',
      'Permanent bridge fabricated in lab',
      'Bridge cemented permanently',
    ],
    benefits: [
      'Fixed — does not come out',
      'Restores chewing ability and speech',
      'Prevents neighboring teeth from shifting',
      'Faster and less costly than implant',
    ],
    aftercare: [
      'Use floss threaders or a water flosser under the bridge',
      'Avoid very sticky or crunchy foods',
      'Regular hygiene visits every 6 months',
    ],
    faq: [
      { q: 'How is this different from an implant?', a: 'A bridge requires reshaping the neighboring teeth as anchors. An implant stands alone and does not affect neighbors.' },
      { q: 'How long does it last?', a: 'A well-maintained bridge lasts 10–15 years.' },
    ],
    image_query: 'dental bridge missing tooth restoration',
    consent_required: false,
    tags: ['restorative', 'fixed', 'bridge'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'night-guard',
    industry: 'dental',
    category: 'preventive',
    name: 'Custom Night Guard (Bruxism)',
    description: 'A custom-fitted oral appliance worn during sleep to protect teeth from grinding and clenching.',
    duration_min: 30,
    plain_english: 'If you grind your teeth at night, it slowly wears them down and can cause jaw pain and cracked teeth. A custom night guard acts as a protective cushion — stopping the damage while you sleep.',
    steps: [
      'Digital impressions or traditional molds taken',
      'Lab fabricates guard to your exact bite',
      'Guard fitted and adjusted at delivery appointment',
    ],
    benefits: [
      'Protects enamel from grinding wear',
      'Reduces jaw pain and headaches',
      'Prevents cracked and fractured teeth',
      'Improves sleep quality for many patients',
    ],
    aftercare: [
      'Wear every night',
      'Clean with a toothbrush and cold water — never hot',
      'Store in case when not in use',
      'Replace every 2–5 years depending on grinding severity',
    ],
    faq: [
      { q: 'How do I know if I grind?', a: 'Signs include worn tooth edges, jaw pain in the morning, frequent headaches, and broken fillings. Your dentist can spot wear patterns on your teeth.' },
      { q: 'Can I buy one from the store?', a: 'Over-the-counter guards are soft and bulky — they can actually worsen grinding. Custom guards are precisely fitted and far more effective.' },
    ],
    image_query: 'custom night guard bruxism teeth grinding',
    consent_required: false,
    tags: ['preventive', 'bruxism', 'custom', 'non-surgical'],
    created_at: new Date().toISOString(),
  },
]

// ─────────────────────────────────────────────
// SALON — 10 procedures
// ─────────────────────────────────────────────
export const SALON_PROCEDURES: Procedure[] = [
  {
    id: 'balayage',
    industry: 'salon',
    category: 'color',
    name: 'Balayage Color',
    description: 'Hand-painted highlighting technique that creates a natural, sun-kissed gradient effect.',
    duration_min: 150,
    plain_english: 'We hand-paint color onto your hair to create natural-looking, low-maintenance highlights that grow out beautifully — no harsh lines at the roots.',
    steps: [
      'Consultation and color selection',
      'Hair sectioned',
      'Color hand-painted onto sections',
      'Processing time (30–45 min)',
      'Toner applied for tone refinement',
      'Blow-dry and style',
    ],
    benefits: [
      'Natural, sun-kissed look',
      'Low-maintenance — grows out gracefully',
      'Fully customizable to your skin tone',
      'No harsh root lines',
    ],
    aftercare: [
      'Use color-safe, sulfate-free shampoo',
      'Deep condition weekly',
      'Avoid washing for 48 hours after service',
      'Touch-ups every 3–4 months',
    ],
    faq: [
      { q: 'How is balayage different from highlights?', a: 'Balayage is hand-painted for a softer, more natural look. Traditional highlights use foils for more uniform lift.' },
      { q: 'How often do I need to come back?', a: 'Every 3–4 months, compared to 6–8 weeks for traditional highlights.' },
    ],
    image_query: 'balayage hair color transformation',
    consent_required: false,
    tags: ['color', 'highlights', 'low-maintenance'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'full-highlights',
    industry: 'salon',
    category: 'color',
    name: 'Full Foil Highlights',
    description: 'Foil highlights applied throughout the entire head for a bright, dimensional color result.',
    duration_min: 120,
    plain_english: 'We apply lightener to sections of your hair wrapped in foil throughout your entire head — giving you bright, uniform highlights with a more dramatic color change than balayage.',
    steps: [
      'Color consultation and strand test if needed',
      'Hair sectioned into quadrants',
      'Lightener applied to foil sections',
      'Processing time (30–45 min)',
      'Foils removed and hair rinsed',
      'Toner applied for desired tone',
      'Blow-dry and style',
    ],
    benefits: [
      'More dramatic color lift than balayage',
      'Uniform brightness throughout',
      'Great for going significantly lighter',
      'Complements a range of base colors',
    ],
    aftercare: [
      'Use purple shampoo weekly to keep tone cool',
      'Deep condition every 1–2 weeks',
      'Avoid chlorine and direct sun without UV protection spray',
      'Touch-ups every 6–8 weeks',
    ],
    faq: [
      { q: 'Will it damage my hair?', a: 'Chemical services affect hair structure, which is why we perform strand tests and use bond-building treatments when needed.' },
      { q: 'What is the difference between partial and full?', a: 'Partial highlights focus on the top sections framing the face. Full highlights cover the entire head for a more complete look.' },
    ],
    image_query: 'foil highlights hair salon transformation',
    consent_required: false,
    tags: ['color', 'highlights', 'lightening'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'single-process-color',
    industry: 'salon',
    category: 'color',
    name: 'Single Process Color (Root-to-Tip)',
    description: 'One shade applied evenly from root to tip — covers gray or changes overall color.',
    duration_min: 90,
    plain_english: 'We apply one color evenly to your entire head — perfect for covering gray, going darker, or making a complete color change. In and out in under two hours with a fully refreshed look.',
    steps: [
      'Consultation and color selection',
      'Color formula mixed',
      'Applied root-to-tip',
      'Processing time (25–45 min)',
      'Rinsed and conditioned',
      'Blow-dry and style',
    ],
    benefits: [
      'Complete, even color coverage',
      'Best option for 100% gray coverage',
      'Wide range of shades available',
      'Fast, predictable results',
    ],
    aftercare: [
      'Wait 48 hours before first wash',
      'Use color-safe shampoo only',
      'Cold water rinse preserves color longer',
      'Touch-up roots every 4–6 weeks',
    ],
    faq: [
      { q: 'Can I go lighter with a single process?', a: 'Single process adds color — it cannot lift/lighten. Lightening requires bleach, which is a separate service.' },
      { q: 'How well does it cover gray?', a: 'Professional color provides excellent gray coverage. We select a formula specifically for your gray percentage.' },
    ],
    image_query: 'single process hair color salon gray coverage',
    consent_required: false,
    tags: ['color', 'gray-coverage', 'all-over'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'keratin-treatment',
    industry: 'salon',
    category: 'chemical',
    name: 'Keratin Smoothing Treatment',
    description: 'A professional smoothing treatment that eliminates frizz and reduces curl for 3–5 months.',
    duration_min: 180,
    plain_english: 'Keratin treatments infuse your hair with a smoothing protein that eliminates frizz and dramatically reduces curl — giving you smooth, shiny, manageable hair for months without daily effort.',
    steps: [
      'Clarifying shampoo wash',
      'Keratin solution applied section by section',
      'Processing time (20–30 min)',
      'Blow-dried straight while sealing in treatment',
      'Flat iron passes to lock keratin in',
      'Client leaves with hair down — no getting wet for 72 hours',
    ],
    benefits: [
      'Eliminates frizz for 3–5 months',
      'Dramatically reduces blow-dry time daily',
      'Adds shine and softness',
      'Works on all hair types',
    ],
    aftercare: [
      'Do not wash, wet, or tie hair for 72 hours',
      'Use sulfate-free shampoo and conditioner',
      'Avoid chlorine pools — shortens results',
      'No ponytails or clips for the first 72 hours',
    ],
    faq: [
      { q: 'Will it straighten my hair completely?', a: 'Brazilian keratin reduces volume and frizz but does not fully straighten. If you want bone-straight, ask about a Japanese straightening treatment.' },
      { q: 'Is it safe for color-treated hair?', a: 'Yes — keratin is safe on color-treated hair and can actually enhance shine and color vibrancy.' },
      { q: 'How long does it last?', a: 'Typically 3–5 months depending on your hair type, how often you wash, and whether you use sulfate-free products.' },
    ],
    image_query: 'keratin treatment smooth shiny hair before after',
    consent_required: true,
    tags: ['chemical', 'smoothing', 'anti-frizz'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'perm',
    industry: 'salon',
    category: 'chemical',
    name: 'Perm (Permanent Wave)',
    description: 'Chemical treatment that restructures hair into lasting curls or waves.',
    duration_min: 150,
    plain_english: 'A perm uses a chemical process to permanently reshape your hair into curls or waves — waking up with effortless texture every day without heat styling.',
    steps: [
      'Consultation on curl size and pattern',
      'Hair wrapped around rods',
      'Perming solution applied',
      'Processing time (20–40 min)',
      'Neutralizer applied to lock in curl',
      'Rods removed, hair rinsed',
      'Air-dry or diffuse only',
    ],
    benefits: [
      'Permanent curl texture — no daily styling',
      'Adds volume to fine, limp hair',
      'Customizable curl size (tight ringlets to loose waves)',
      'Results last 3–6 months',
    ],
    aftercare: [
      'Do not wash for 48 hours',
      'Use sulfate-free, curl-specific products',
      'Scrunch — do not brush curls',
      'Deep condition weekly',
      'Avoid excessive heat styling',
    ],
    faq: [
      { q: 'Will it damage my hair?', a: 'Perms change the hair structure — they require some chemical processing. We assess your hair health first and use bond builders to minimize stress.' },
      { q: 'Can I color my hair and perm at the same time?', a: 'We recommend spacing these services by at least 2 weeks to protect hair integrity.' },
    ],
    image_query: 'perm curls waves hair transformation',
    consent_required: true,
    tags: ['chemical', 'curls', 'waves', 'texture'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'haircut-restyle',
    industry: 'salon',
    category: 'cuts',
    name: 'Haircut & Restyle',
    description: 'Personalized cut tailored to your face shape, lifestyle, and hair texture.',
    duration_min: 60,
    plain_english: 'A great haircut is not just about removing length — it is a shape designed specifically for your face, your hair type, and how much time you actually want to spend styling every morning.',
    steps: [
      'Consultation on goals and lifestyle',
      'Shampoo and condition',
      'Cut performed on wet or dry hair as needed',
      'Blow-dry and style',
      'Finishing product applied',
    ],
    benefits: [
      'Shape designed for your face',
      'Removes split ends and damage',
      'Easier daily styling',
      'Enhances your natural texture',
    ],
    aftercare: [
      'Trim every 6–8 weeks to maintain shape',
      'Ask stylist for a personalized product recommendation',
    ],
    faq: [
      { q: 'How often should I get a trim?', a: 'Every 6–8 weeks for short styles. Every 10–12 weeks for longer lengths.' },
      { q: 'Should I come in with clean hair?', a: 'You can come as you are — we shampoo before the cut.' },
    ],
    image_query: 'professional haircut salon style transformation',
    consent_required: false,
    tags: ['cuts', 'restyle', 'trim'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'tape-in-extensions',
    industry: 'salon',
    category: 'extensions',
    name: 'Tape-In Hair Extensions',
    description: 'Weft extensions attached with medical-grade adhesive tape for a flat, natural look.',
    duration_min: 120,
    plain_english: 'Tape-in extensions add length and volume using thin, flat panels that sandwich around your real hair — they look completely natural and can be styled just like your own hair.',
    steps: [
      'Consultation — length, volume, and color match',
      'Hair sectioned near nape',
      'Tape wefts sandwiched around small sections',
      'Pressed to secure adhesive',
      'Cut and blended to match your natural hair',
    ],
    benefits: [
      'Lay completely flat — invisible bond',
      'Reusable for 4–6 installs with new tape',
      'Can be heat styled and colored (if human hair)',
      'Added in 1–2 hours',
    ],
    aftercare: [
      'Use sulfate-free shampoo to preserve adhesive',
      'Do not apply conditioner near the bonds',
      'Brush gently from mid-length down first',
      'Move-up appointment every 6–8 weeks',
    ],
    faq: [
      { q: 'Will they damage my hair?', a: 'When installed and removed correctly, tape extensions cause minimal damage.' },
      { q: 'Can I swim or work out?', a: 'Yes, but rinse hair after swimming and braid it during intense workouts to reduce slippage.' },
    ],
    image_query: 'tape in hair extensions before after length',
    consent_required: true,
    tags: ['extensions', 'length', 'volume'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'olaplex-treatment',
    industry: 'salon',
    category: 'treatments',
    name: 'Olaplex Bond Repair Treatment',
    description: 'Molecular bond-building treatment that repairs damage from chemical services, heat, and breakage.',
    duration_min: 45,
    plain_english: 'Olaplex reconnects the broken bonds inside your hair that cause damage, breakage, and dullness — it is like a structural repair for your hair from the inside out.',
    steps: [
      'Olaplex No.1 mixed into color or bleach (during chemical service) or applied standalone',
      'Olaplex No.2 applied as a conditioning mask',
      'Processed for 10–20 minutes',
      'Rinsed and styled',
    ],
    benefits: [
      'Repairs chemical and heat damage at molecular level',
      'Reduces breakage dramatically',
      'Allows for more aggressive lightening safely',
      'Leaves hair feeling stronger and softer',
    ],
    aftercare: [
      'Use Olaplex No.3 at home weekly',
      'Follow with sulfate-free shampoo',
      'Reduce heat styling to preserve bonds',
    ],
    faq: [
      { q: 'Is this the same as a deep conditioner?', a: 'No — Olaplex works inside the hair strand to repair broken disulfide bonds. Conditioners only coat the surface.' },
      { q: 'Can I add it to my color service?', a: 'Yes — and we recommend it. Adding Olaplex during color or bleach significantly protects your hair during the service.' },
    ],
    image_query: 'Olaplex bond repair treatment healthy hair',
    consent_required: false,
    tags: ['treatment', 'repair', 'bond-building'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'scalp-treatment',
    industry: 'salon',
    category: 'treatments',
    name: 'Scalp Treatment & Massage',
    description: 'Targeted scalp treatment addressing dryness, flaking, oil buildup, or hair thinning.',
    duration_min: 45,
    plain_english: 'Healthy hair starts at the scalp. We apply targeted serums and perform a relaxing scalp massage that increases blood flow, removes buildup, and creates the ideal environment for hair growth.',
    steps: [
      'Scalp analysis',
      'Clarifying scalp scrub applied',
      'Treatment serum applied to problem areas',
      'Scalp massage (10–15 min)',
      'Rinse and condition',
    ],
    benefits: [
      'Reduces dandruff and dryness',
      'Removes product and oil buildup',
      'Stimulates blood flow for hair growth',
      'Deeply relaxing experience',
    ],
    aftercare: [
      'Avoid harsh shampoos between treatments',
      'Use prescribed scalp serum at home',
      'Monthly maintenance recommended',
    ],
    faq: [
      { q: 'Can this help with hair loss?', a: 'Scalp massage increases blood circulation which can support healthier hair growth. For significant hair thinning, we can recommend additional options.' },
    ],
    image_query: 'scalp treatment salon hair growth massage',
    consent_required: false,
    tags: ['treatment', 'scalp', 'hair-growth'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'vivid-color',
    industry: 'salon',
    category: 'color',
    name: 'Vivid / Fashion Color',
    description: 'Bold, statement color in non-natural shades — pastel, neon, jewel tones, or color melts.',
    duration_min: 180,
    plain_english: 'Vivid color is fashion-forward, expressive color in any shade you want — from pastel pink to deep emerald to electric blue. We lift your hair to the right base first, then apply your chosen shade for a true, vibrant result.',
    steps: [
      'Consultation on target shade and inspiration',
      'Hair lifted to appropriate base (often platinum)',
      'Vivid color applied',
      'Processing time',
      'Gloss or toner if needed',
      'Blow-dry and style',
    ],
    benefits: [
      'Fully expressive, personalized color',
      'Professional-grade pigments fade gracefully',
      'Can be customized into color melts and multitones',
      'Unique, head-turning results',
    ],
    aftercare: [
      'Use color-safe, sulfate-free products',
      'Wash with cool water to preserve vibrancy',
      'Avoid prolonged sun exposure',
      'Touch-up every 4–8 weeks depending on shade',
    ],
    faq: [
      { q: 'Will it damage my hair going this light first?', a: 'Pre-lightening does affect hair health — we use Olaplex and bond builders to protect your hair during the lift.' },
      { q: 'How quickly will it fade?', a: 'Vivid colors fade faster than natural tones. Reds and oranges last longest; pinks and purples fade fastest. Proper home care extends results significantly.' },
    ],
    image_query: 'vivid fashion hair color pastel neon salon',
    consent_required: true,
    tags: ['color', 'vivid', 'fashion', 'creative'],
    created_at: new Date().toISOString(),
  },
]

// ─────────────────────────────────────────────
// COSMETIC SURGERY — 10 procedures
// ─────────────────────────────────────────────
export const COSMETIC_PROCEDURES: Procedure[] = [
  {
    id: 'rhinoplasty',
    industry: 'cosmetic',
    category: 'facial',
    name: 'Rhinoplasty (Nose Reshaping)',
    description: 'Surgical procedure to reshape the nose for aesthetic or functional improvement.',
    duration_min: 180,
    plain_english: 'Rhinoplasty reshapes your nose to better match your facial features — whether that\'s reducing the size, refining the tip, or correcting a deviated septum that affects breathing.',
    steps: [
      'Consultation and 3D imaging simulation',
      'Medical clearance',
      'General or local anesthesia with sedation',
      'Incisions made inside nostrils (closed) or across the base (open)',
      'Bone and cartilage reshaped',
      'Incisions closed, splint applied',
      '1–2 week recovery with splint',
    ],
    benefits: [
      'Permanent results',
      'Improves facial harmony and proportion',
      'Can correct breathing issues simultaneously',
      'High patient satisfaction rate',
    ],
    aftercare: [
      'Splint worn for 1–2 weeks',
      'No strenuous activity for 3–4 weeks',
      'Sleep with head elevated for 2 weeks',
      'Avoid sun exposure on nose for 6 months',
      'Final results visible at 12 months',
    ],
    faq: [
      { q: 'How long until I see final results?', a: 'Swelling resolves over 12 months — most patients see ~80% of results at 3 months.' },
      { q: 'Is it painful?', a: 'Discomfort is well-managed with prescribed medication. Most patients describe it as pressure, not pain.' },
      { q: 'How old do I need to be?', a: 'We recommend waiting until facial growth is complete — typically 16–18 for females, 17–19 for males.' },
    ],
    image_query: 'rhinoplasty nose reshaping before after profile',
    consent_required: true,
    tags: ['surgical', 'facial', 'permanent'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'hair-transplant',
    industry: 'cosmetic',
    category: 'hair',
    name: 'FUE Hair Transplant',
    description: 'Follicular Unit Extraction — individual hair follicles transplanted to restore natural hairline.',
    duration_min: 480,
    plain_english: 'We individually extract healthy hair follicles from the back of your head — where hair is permanent — and precisely implant them in thinning or bald areas to restore a natural-looking hairline.',
    steps: [
      'Hairline design consultation',
      'Donor area shaved and numbed',
      'Follicles individually extracted with micro-punch',
      'Recipient sites created at correct angle and density',
      'Follicles implanted one by one',
      'Healing begins immediately',
    ],
    benefits: [
      'Permanent, natural-looking results',
      'Uses your own hair — no rejection',
      'No linear scar',
      'Can style and cut normally after healing',
    ],
    aftercare: [
      'Sleep upright for 3–5 days',
      'No touching the grafts for 2 weeks',
      'Shedding at 2–4 weeks is normal (shock loss)',
      'New growth visible at 4–6 months',
      'Full results at 12–18 months',
    ],
    faq: [
      { q: 'When will I see results?', a: 'Hair begins growing at 4–6 months. Full, final results are visible at 12–18 months.' },
      { q: 'Is the transplanted hair permanent?', a: 'Yes — follicles from the donor zone are genetically resistant to hair loss.' },
      { q: 'How many grafts do I need?', a: 'Varies by area — typically 1,500–3,500 grafts for hairline restoration. We assess during consultation.' },
    ],
    image_query: 'hair transplant FUE before after hairline',
    consent_required: true,
    tags: ['surgical', 'hair', 'permanent'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'breast-augmentation',
    industry: 'cosmetic',
    category: 'breast',
    name: 'Breast Augmentation',
    description: 'Surgical placement of implants to enhance breast size, shape, and symmetry.',
    duration_min: 120,
    plain_english: 'We use implants or fat transfer to enhance your breast size and shape — creating natural-feeling results tailored to your body type and goals.',
    steps: [
      'Consultation — size, shape, and implant type selection',
      '3D imaging simulation',
      'Medical clearance and pre-op labs',
      'General anesthesia administered',
      'Incision made (typically in crease)',
      'Implant placed and positioned',
      'Incisions closed, surgical bra fitted',
    ],
    benefits: [
      'Significant, customizable enhancement',
      'Improves symmetry',
      'Natural look and feel with modern implants',
      'High patient satisfaction',
    ],
    aftercare: [
      'Wear surgical bra 24/7 for 4–6 weeks',
      'No lifting over 10 lbs for 4 weeks',
      'No strenuous activity for 6 weeks',
      'Sleep on back for 6 weeks',
      'Scar maturation takes 12–18 months',
    ],
    faq: [
      { q: 'How long do implants last?', a: 'Modern implants are designed to last 10–20 years. Replacement is not automatically required but may be desired.' },
      { q: 'Saline vs. silicone?', a: 'Silicone implants feel more natural and are the most popular choice. We discuss both options in your consultation.' },
      { q: 'Will I lose nipple sensation?', a: 'Temporary changes in sensation are possible. Most patients return to normal feeling within 3–6 months.' },
    ],
    image_query: 'breast augmentation before after natural results',
    consent_required: true,
    tags: ['surgical', 'breast', 'enhancement'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'breast-lift',
    industry: 'cosmetic',
    category: 'breast',
    name: 'Breast Lift (Mastopexy)',
    description: 'Reshapes and elevates the breast by removing excess skin and repositioning the nipple.',
    duration_min: 150,
    plain_english: 'A breast lift restores a youthful, perky position to breasts that have sagged from pregnancy, weight changes, or aging — without necessarily changing the size.',
    steps: [
      'Consultation and candidacy assessment',
      'Surgical markings made pre-op',
      'General anesthesia',
      'Incisions made (pattern depends on degree of lift needed)',
      'Excess skin removed, tissue reshaped',
      'Nipple repositioned higher on breast',
      'Incisions closed with dissolvable sutures',
    ],
    benefits: [
      'Restores youthful breast position',
      'Improves bra fit',
      'Can be combined with augmentation for volume + lift',
      'Long-lasting when weight is stable',
    ],
    aftercare: [
      'Surgical bra for 6 weeks',
      'Avoid raising arms above head for 2 weeks',
      'No strenuous exercise for 6 weeks',
      'Scar treatment begins at 6 weeks post-op',
    ],
    faq: [
      { q: 'Will I need implants too?', a: 'A lift restores shape and position. If you also want more volume, combining with implants is common. We assess this in consultation.' },
      { q: 'How visible are the scars?', a: 'Scars fade significantly over 1–2 years. Their placement is designed to be concealed by a bra or swimsuit.' },
    ],
    image_query: 'breast lift mastopexy before after results',
    consent_required: true,
    tags: ['surgical', 'breast', 'lift', 'reshaping'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'blepharoplasty',
    industry: 'cosmetic',
    category: 'facial',
    name: 'Blepharoplasty (Eyelid Surgery)',
    description: 'Removes excess skin and fat from upper and/or lower eyelids to create a more rested, youthful appearance.',
    duration_min: 120,
    plain_english: 'Eyelid surgery removes the drooping or puffy skin around your eyes that makes you look tired — results look completely natural, and most people just say you look well-rested.',
    steps: [
      'Consultation and eyelid assessment',
      'Local anesthesia with sedation',
      'Upper lid: incision in natural crease, excess skin removed',
      'Lower lid: fat repositioned or removed through incision below lash line',
      'Sutures placed',
      'Cool compresses applied',
    ],
    benefits: [
      'Dramatically more rested, alert appearance',
      'Can improve vision blocked by heavy upper lids',
      'Natural-looking results',
      'Long-lasting — 5–10 years typically',
    ],
    aftercare: [
      'Cool compresses for 48 hours',
      'Head elevated to reduce swelling',
      'No strenuous activity for 2 weeks',
      'Avoid contacts for 2 weeks',
      'Sutures out at 1 week',
    ],
    faq: [
      { q: 'Will I look different or just rested?', a: 'Most patients look like the best, most rested version of themselves — not changed. Results are subtle and natural.' },
      { q: 'Is the upper lid different from the lower?', a: 'Yes. Upper blepharoplasty addresses drooping skin. Lower focuses on puffiness and bags from fat herniation.' },
    ],
    image_query: 'blepharoplasty eyelid surgery before after rested',
    consent_required: true,
    tags: ['surgical', 'facial', 'eyelid', 'rejuvenation'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'facelift',
    industry: 'cosmetic',
    category: 'facial',
    name: 'Facelift (Rhytidectomy)',
    description: 'Surgical repositioning of facial tissue to reduce sagging, deep folds, and jowls.',
    duration_min: 240,
    plain_english: 'A facelift repositions the underlying facial tissue and removes excess skin to restore a naturally youthful contour — not a pulled or frozen look, but a refreshed version of you.',
    steps: [
      'Consultation and facial analysis',
      'Medical clearance',
      'General anesthesia or IV sedation',
      'Incisions in hairline and around ears',
      'Underlying SMAS tissue repositioned',
      'Excess skin trimmed',
      'Incisions closed',
    ],
    benefits: [
      'Most comprehensive facial rejuvenation available',
      'Addresses jowls, nasolabial folds, and neck laxity',
      'Results last 10+ years',
      'Natural-looking when performed correctly',
    ],
    aftercare: [
      'Head elevated for 2 weeks',
      'Drains removed at 1–2 days post-op',
      'Sutures out at 1 week',
      'No strenuous activity for 4 weeks',
      'Full swelling resolution at 3–6 months',
    ],
    faq: [
      { q: 'Will I look unnatural?', a: 'Modern facelifts lift underlying tissue, not just skin — results look natural, not "stretched."' },
      { q: 'How long do results last?', a: 'Most patients enjoy results for 10–15 years before considering a revision.' },
    ],
    image_query: 'facelift rhytidectomy before after natural results',
    consent_required: true,
    tags: ['surgical', 'facial', 'rejuvenation', 'anti-aging'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'liposuction',
    industry: 'cosmetic',
    category: 'body',
    name: 'Liposuction',
    description: 'Surgical removal of localized fat deposits to contour and reshape targeted body areas.',
    duration_min: 120,
    plain_english: 'Liposuction removes stubborn pockets of fat that do not respond to diet or exercise — sculpting areas like the abdomen, flanks, thighs, and arms for a more defined contour.',
    steps: [
      'Consultation and area mapping',
      'Medical clearance',
      'Anesthesia administered',
      'Tumescent fluid injected to numb and constrict blood vessels',
      'Cannula inserted through small incisions',
      'Fat suctioned out',
      'Compression garment applied immediately',
    ],
    benefits: [
      'Permanent removal of fat cells in targeted area',
      'Visible contouring results',
      'Multiple areas treated in one session',
      'Minimal scarring from small incisions',
    ],
    aftercare: [
      'Compression garment worn 24/7 for 4–6 weeks',
      'Swelling normal for 3–6 months',
      'Light walking from day 1',
      'No strenuous activity for 4 weeks',
      'Maintain stable weight for best results',
    ],
    faq: [
      { q: 'Will the fat come back?', a: 'The fat cells are permanently removed. However, remaining cells can enlarge with weight gain. Maintaining a stable weight preserves results.' },
      { q: 'Is it a weight loss procedure?', a: 'No — liposuction is a body contouring procedure. Ideal candidates are near their goal weight with specific stubborn areas.' },
    ],
    image_query: 'liposuction body contouring before after abdomen',
    consent_required: true,
    tags: ['surgical', 'body', 'contouring', 'fat-removal'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'tummy-tuck',
    industry: 'cosmetic',
    category: 'body',
    name: 'Tummy Tuck (Abdominoplasty)',
    description: 'Removes excess abdominal skin, tightens separated muscles, and creates a flatter midsection.',
    duration_min: 180,
    plain_english: 'A tummy tuck removes the loose, excess skin and tightens the abdominal muscles that often separate after pregnancy or major weight loss — creating a flat, firm midsection that diet and exercise alone cannot achieve.',
    steps: [
      'Consultation and abdominal assessment',
      'Medical clearance',
      'General anesthesia',
      'Hip-to-hip incision made low (hidden by underwear)',
      'Separated abdominal muscles repaired and tightened',
      'Excess skin removed',
      'Navel repositioned naturally',
      'Incision closed, drains placed',
    ],
    benefits: [
      'Flat, toned abdominal profile',
      'Repairs muscle separation (diastasis recti)',
      'Removes hanging skin after weight loss',
      'Long-lasting with stable weight',
    ],
    aftercare: [
      'Drains in place for 1–2 weeks',
      'Compression garment for 6 weeks',
      'No strenuous activity for 6 weeks',
      'Walking encouraged from day 1 (hunched at first)',
      'Scar fades over 12–18 months',
    ],
    faq: [
      { q: 'Is this right for me after pregnancy?', a: 'Tummy tuck is one of the most common post-pregnancy procedures. We recommend waiting until you are done having children.' },
      { q: 'Will there be a visible scar?', a: 'The incision is placed low — below the underwear line. Over time it fades to a fine, pale line.' },
    ],
    image_query: 'tummy tuck abdominoplasty before after flat stomach',
    consent_required: true,
    tags: ['surgical', 'body', 'abdomen', 'skin-removal'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'botox',
    industry: 'cosmetic',
    category: 'injectables',
    name: 'Botox / Neuromodulator Injections',
    description: 'Injectable neurotoxin that temporarily relaxes facial muscles to smooth dynamic wrinkles.',
    duration_min: 30,
    plain_english: 'Botox temporarily relaxes the muscles that cause forehead lines, frown lines, and crow\'s feet — smoothing wrinkles for 3–4 months without any downtime or surgery.',
    steps: [
      'Consultation and facial movement assessment',
      'Injection sites marked',
      'Small needles inject precisely dosed neuromodulator',
      'Ice applied post-injection',
      'Done in under 15 minutes',
    ],
    benefits: [
      'No surgery, no downtime',
      'Visibly smoother forehead and eye area',
      'Results in 3–7 days',
      'Safe and predictable with experienced injector',
      'Preventive when started early',
    ],
    aftercare: [
      'Do not lie down for 4 hours',
      'No intense exercise for 24 hours',
      'Do not massage or rub treated areas',
      'Avoid facials for 2 weeks',
    ],
    faq: [
      { q: 'Will I look frozen?', a: 'With the correct dose, you look refreshed — not frozen. Over-injection causes that look; proper dosing preserves natural expression.' },
      { q: 'How long does it last?', a: 'Typically 3–4 months. Regular treatment can extend intervals over time.' },
      { q: 'Does it hurt?', a: 'Most patients describe it as a small pinch. We can apply numbing cream beforehand.' },
    ],
    image_query: 'botox injectable wrinkle treatment before after forehead',
    consent_required: true,
    tags: ['injectables', 'non-surgical', 'anti-aging', 'no-downtime'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'dermal-fillers',
    industry: 'cosmetic',
    category: 'injectables',
    name: 'Dermal Fillers',
    description: 'Hyaluronic acid gel injections that restore volume to the lips, cheeks, jawline, and nasolabial folds.',
    duration_min: 45,
    plain_english: 'Fillers use a naturally-occurring gel to restore the volume your face loses with age — plumping lips, lifting cheeks, defining the jawline, or smoothing deep lines. Results are immediate and can last 6–24 months.',
    steps: [
      'Consultation and target area assessment',
      'Topical numbing cream applied (15 min)',
      'Filler injected with fine needle or cannula',
      'Area massaged for even distribution',
      'Ice applied to reduce swelling',
    ],
    benefits: [
      'Immediate, visible results',
      'No surgery or downtime',
      'Reversible with hyaluronidase if desired',
      'Natural-looking volume restoration',
      'Lasts 6–18 months depending on area',
    ],
    aftercare: [
      'Avoid touching or massaging for 6 hours',
      'No strenuous exercise for 24 hours',
      'Sleep on back to avoid displacement',
      'Minor bruising and swelling resolves in 3–5 days',
    ],
    faq: [
      { q: 'Can fillers be reversed?', a: 'Yes — hyaluronic acid fillers can be dissolved with hyaluronidase at any time.' },
      { q: 'How is this different from Botox?', a: 'Botox relaxes muscles to smooth wrinkles. Fillers add volume to restore fullness and structure.' },
      { q: 'Will my lips look overdone?', a: 'With conservative dosing and an experienced injector, lip filler looks natural. We always recommend starting conservatively.' },
    ],
    image_query: 'dermal fillers lip cheek volume before after natural',
    consent_required: true,
    tags: ['injectables', 'non-surgical', 'volume', 'lips', 'cheeks'],
    created_at: new Date().toISOString(),
  },
]

// ─────────────────────────────────────────────
// LANDSCAPING — 8 procedures
// ─────────────────────────────────────────────
export const LANDSCAPING_PROCEDURES: Procedure[] = [
  {
    id: 'landscape-design',
    industry: 'landscaping',
    category: 'design',
    name: 'Custom Landscape Design',
    description: 'Full property design plan including plant selection, hardscape layout, irrigation, and lighting.',
    duration_min: 60,
    plain_english: 'We create a complete visual plan for your property — from plant placement and pathways to lighting and water features — so you can see exactly what your yard will look like before we break ground.',
    steps: [
      'On-site property assessment and measurements',
      'Client style and goal interview',
      '2D or 3D design concept created',
      'Plant and material selection',
      'Design presented with cost estimate',
      'Revisions and approval',
    ],
    benefits: [
      'See your project before any work begins',
      'Cohesive plan avoids costly mistakes',
      'Tailored to your lifestyle, climate, and budget',
      'Increases property value',
    ],
    aftercare: [
      'Regular watering schedule established at install',
      'Seasonal maintenance plan recommended',
      'Annual design review to add or adjust elements',
    ],
    faq: [
      { q: 'What does the design include?', a: 'A full design includes plant layout, hardscape elements, irrigation plan, lighting suggestions, and a phased implementation plan if budget requires.' },
      { q: 'Can I just get the design and do the work myself?', a: 'Yes — we can provide the design plan only. Many clients phase their projects and install elements over time.' },
    ],
    image_query: 'custom landscape design 3D rendering backyard',
    consent_required: false,
    tags: ['design', 'planning', 'consultation'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'patio-installation',
    industry: 'landscaping',
    category: 'hardscape',
    name: 'Patio Installation',
    description: 'Custom paver or concrete patio designed and installed for outdoor living space.',
    duration_min: 60,
    plain_english: 'We design and install a beautiful, durable patio that extends your living space outdoors — from intimate seating areas to large entertainment spaces with fire pits and outdoor kitchens.',
    steps: [
      'Site assessment and measurements',
      'Material selection (pavers, concrete, flagstone, etc.)',
      'Design and layout plan',
      'Ground excavation and base preparation',
      'Patio installed and leveled',
      'Edge restraints and jointing sand or grout applied',
      'Final walkthrough and sealing',
    ],
    benefits: [
      'Durable, long-lasting outdoor surface',
      'Dramatically increases usable outdoor space',
      'Wide range of materials and styles',
      'Increases home value significantly',
    ],
    aftercare: [
      'Seal pavers annually to prevent staining',
      'Re-sand joints as needed after winter',
      'Sweep regularly to prevent organic buildup',
    ],
    faq: [
      { q: 'How long does installation take?', a: 'A typical patio project takes 2–5 days depending on size and material.' },
      { q: 'What materials do you recommend?', a: 'Concrete pavers offer the best combination of durability, aesthetics, and value. We walk through all options with pricing at your consultation.' },
    ],
    image_query: 'paver patio installation backyard outdoor living',
    consent_required: false,
    tags: ['hardscape', 'patio', 'pavers', 'outdoor-living'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'retaining-wall',
    industry: 'landscaping',
    category: 'hardscape',
    name: 'Retaining Wall Construction',
    description: 'Engineered retaining wall to manage slopes, prevent erosion, and create usable terraced space.',
    duration_min: 60,
    plain_english: 'Retaining walls turn a sloped, unusable yard into flat, functional space — while preventing soil erosion and protecting your foundation. We engineer walls to last decades, not years.',
    steps: [
      'Site evaluation and slope assessment',
      'Engineering calculations for wall height',
      'Material selection (block, natural stone, timber)',
      'Excavation and footing installed',
      'Wall constructed with proper drainage behind',
      'Backfill and grading',
      'Final inspection',
    ],
    benefits: [
      'Creates flat, usable space on slopes',
      'Prevents soil erosion and runoff',
      'Protects foundation from water damage',
      'Adds architectural interest to the landscape',
    ],
    aftercare: [
      'Inspect drainage outlets annually',
      'Monitor for shifting or bulging after heavy rain',
      'Keep vegetation trimmed away from wall base',
    ],
    faq: [
      { q: 'Do I need a permit?', a: 'Walls over 3–4 feet typically require a permit in most jurisdictions. We handle the permitting process.' },
      { q: 'How long do retaining walls last?', a: 'Properly engineered and installed walls with good drainage last 20–50 years.' },
    ],
    image_query: 'retaining wall landscaping terraced garden slope',
    consent_required: false,
    tags: ['hardscape', 'retaining-wall', 'grading', 'erosion'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'irrigation-system',
    industry: 'landscaping',
    category: 'irrigation',
    name: 'Irrigation System Installation',
    description: 'Automated in-ground sprinkler or drip irrigation system designed for your specific plant zones.',
    duration_min: 60,
    plain_english: 'An irrigation system waters your lawn and plants automatically — at the right time, in the right amounts, by zone. It saves water, saves time, and keeps everything green even when you are away.',
    steps: [
      'Property walk and zone mapping',
      'Water pressure and flow test',
      'System design (spray vs. drip by zone)',
      'Trenching and pipe installation',
      'Sprinkler or emitter heads installed',
      'Controller programmed and tested',
      'Walkthrough with homeowner',
    ],
    benefits: [
      'Saves up to 50% water vs. manual watering',
      'Consistent watering = healthier plants',
      'Fully automated — never forget to water',
      'Smart controller options for weather-based adjustment',
    ],
    aftercare: [
      'Winterize system (blow out) before first freeze',
      'Spring startup inspection annually',
      'Adjust schedules seasonally',
      'Check heads monthly for clogs or breakage',
    ],
    faq: [
      { q: 'Do I need drip or spray?', a: 'Lawn areas use spray heads. Garden beds and shrubs use drip irrigation — far more efficient. Most properties use both.' },
      { q: 'Can I add a smart controller?', a: 'Yes — we recommend smart controllers that adjust automatically based on local weather data. They pay for themselves in water savings.' },
    ],
    image_query: 'irrigation system sprinkler installation lawn',
    consent_required: false,
    tags: ['irrigation', 'automation', 'water-saving'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'sod-installation',
    industry: 'landscaping',
    category: 'lawn',
    name: 'Sod Installation',
    description: 'Instant lawn installation using pre-grown grass rolls, ready to use within weeks.',
    duration_min: 60,
    plain_english: 'Sod gives you an instant, lush lawn in a single day — no waiting months for seed to grow. We prep the soil, lay the sod, and have you walking on it within a few weeks.',
    steps: [
      'Soil testing and amendment if needed',
      'Existing vegetation killed and removed',
      'Ground rototilled and graded',
      'Starter fertilizer applied',
      'Sod pallets laid with staggered seams',
      'Rolled for firm soil contact',
      'Watering schedule established',
    ],
    benefits: [
      'Instant green lawn in one day',
      'Controls erosion immediately',
      'No weed seed period like seeding',
      'Can be installed most of the year',
    ],
    aftercare: [
      'Water 2–3 times daily for first 2 weeks',
      'First mow at 3–4 inches height',
      'No heavy traffic for 3 weeks',
      'Fertilize at 6 weeks after install',
    ],
    faq: [
      { q: 'How quickly can I walk on it?', a: 'Light foot traffic after 2 weeks; normal use after 3–4 weeks once rooted.' },
      { q: 'Sod vs. seed — which is better?', a: 'Sod is instant and has no establishment window for weeds. Seed is less expensive but takes 4–8 weeks and requires careful management.' },
    ],
    image_query: 'sod installation instant green lawn before after',
    consent_required: false,
    tags: ['lawn', 'sod', 'grass', 'instant'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'outdoor-lighting',
    industry: 'landscaping',
    category: 'design',
    name: 'Low-Voltage Landscape Lighting',
    description: 'Professional LED landscape lighting system for pathways, trees, architecture, and accent areas.',
    duration_min: 60,
    plain_english: 'Landscape lighting transforms your property at night — illuminating pathways for safety, uplighting trees for drama, and accenting your home\'s architecture. It is one of the highest ROI outdoor improvements you can make.',
    steps: [
      'Evening walkthrough to identify key areas',
      'Lighting plan designed',
      'Low-voltage wire run and buried',
      'Fixtures installed and aimed',
      'Timer or smart controller programmed',
      'Final nighttime walkthrough with client',
    ],
    benefits: [
      'Dramatically improves curb appeal at night',
      'Increases safety on pathways and steps',
      'Energy-efficient LED fixtures',
      'Smart timer options for automation',
      'Increases perceived home value',
    ],
    aftercare: [
      'Replace bulbs every 3–5 years (most are LED lasting much longer)',
      'Adjust aim after plants grow',
      'Check for shifting or damage after winter',
    ],
    faq: [
      { q: 'How much does it add to my electric bill?', a: 'LED landscape lighting uses very little power — a typical system adds $5–$15 per month.' },
      { q: 'Can I control it from my phone?', a: 'Yes — smart timer controllers allow app-based scheduling and automation.' },
    ],
    image_query: 'landscape lighting outdoor night pathway trees',
    consent_required: false,
    tags: ['design', 'lighting', 'curb-appeal', 'LED'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'tree-planting',
    industry: 'landscaping',
    category: 'lawn',
    name: 'Tree & Shrub Planting',
    description: 'Professional selection, placement, and installation of trees and shrubs for shade, privacy, or aesthetics.',
    duration_min: 60,
    plain_english: 'The right tree in the right place transforms a yard and provides decades of shade, privacy, and beauty. We select the right species for your climate, soil, and goals — and guarantee establishment.',
    steps: [
      'Site assessment — sun, soil, and space evaluation',
      'Species selection based on goals',
      'Planting holes dug to proper depth and width',
      'Soil amendment added',
      'Trees planted and staked if needed',
      'Mulch ring applied',
      'Initial deep watering',
    ],
    benefits: [
      'Shade reduces cooling costs by up to 30%',
      'Privacy screening from neighbors',
      'Increases property value significantly',
      'Wildlife habitat and environmental benefit',
    ],
    aftercare: [
      'Deep water weekly for first full season',
      'Keep mulch ring 2–3 inches away from trunk',
      'Remove stakes after 1 year',
      'Light pruning in dormant season only',
    ],
    faq: [
      { q: 'How fast do trees grow?', a: 'Growth rate varies enormously by species — from 1 foot to 6+ feet per year. We select species matched to your timeline and goals.' },
      { q: 'Do you guarantee the trees?', a: 'We offer a one-year establishment guarantee on all plant material we install.' },
    ],
    image_query: 'tree planting landscape shade privacy installation',
    consent_required: false,
    tags: ['lawn', 'trees', 'planting', 'shade', 'privacy'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'seasonal-cleanup',
    industry: 'landscaping',
    category: 'seasonal',
    name: 'Seasonal Cleanup & Bed Prep',
    description: 'Spring or fall cleanup including debris removal, bed edging, mulching, and plant cutback.',
    duration_min: 60,
    plain_english: 'A seasonal cleanup removes dead material, preps your beds, and applies fresh mulch — giving your landscape a clean, polished look and setting up your plants for a healthy growing season.',
    steps: [
      'Leaf and debris removal',
      'Perennial cutback and cleanup',
      'Bed edge defined and sharpened',
      'Weeds removed from all beds',
      'Fresh mulch applied (2–3 inch depth)',
      'Shrubs lightly pruned as needed',
    ],
    benefits: [
      'Fresh, polished curb appeal',
      'Mulch retains moisture and suppresses weeds',
      'Removes overwintered pest habitat',
      'Sets plants up for vigorous growth',
    ],
    aftercare: [
      'Reapply mulch annually',
      'Follow up with fertilization 2–3 weeks after spring cleanup',
    ],
    faq: [
      { q: 'Spring or fall — which is more important?', a: 'Both serve different purposes. Spring prep sets the growing season. Fall cleanup protects plants through winter and reduces spring workload.' },
      { q: 'How much mulch do you apply?', a: 'We apply 2–3 inches fresh mulch — enough to suppress weeds and retain moisture without suffocating plant roots.' },
    ],
    image_query: 'seasonal landscape cleanup mulch bed edging spring',
    consent_required: false,
    tags: ['seasonal', 'cleanup', 'mulch', 'maintenance'],
    created_at: new Date().toISOString(),
  },
]

// ─────────────────────────────────────────────
// Exports
// ─────────────────────────────────────────────
export const ALL_PROCEDURES = [
  ...DENTAL_PROCEDURES,
  ...SALON_PROCEDURES,
  ...COSMETIC_PROCEDURES,
  ...LANDSCAPING_PROCEDURES,
]

export function getProceduresByIndustry(industry: string) {
  return ALL_PROCEDURES.filter((p) => p.industry === industry)
}

export function getProcedureById(id: string) {
  return ALL_PROCEDURES.find((p) => p.id === id)
}

export function getProceduresByCategory(industry: string, category: string) {
  return ALL_PROCEDURES.filter((p) => p.industry === industry && p.category === category)
}
